// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxnpHM5dx2wvydWSCGRWAJmrXkgSuXY-o',
    appId: '1:827647189745:web:017f0d21e4aecfa5717f50',
    messagingSenderId: '827647189745',
    projectId: 'just-grab-8a0cd',
    authDomain: 'just-grab-8a0cd.firebaseapp.com',
    storageBucket: 'just-grab-8a0cd.appspot.com',
    measurementId: 'G-9FXLTH80FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARR-q-2v5HP9p1EtlbUSMCjTebyf4a_Ag',
    appId: '1:827647189745:android:58470b4977b0c259717f50',
    messagingSenderId: '827647189745',
    projectId: 'just-grab-8a0cd',
    storageBucket: 'just-grab-8a0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOu59hm5tyE3QzOCjHQg1VSIEhPLjRCcM',
    appId: '1:827647189745:ios:ea71c2d07bef1c2c717f50',
    messagingSenderId: '827647189745',
    projectId: 'just-grab-8a0cd',
    storageBucket: 'just-grab-8a0cd.appspot.com',
    iosBundleId: 'com.example.justgrabDine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOu59hm5tyE3QzOCjHQg1VSIEhPLjRCcM',
    appId: '1:827647189745:ios:ea71c2d07bef1c2c717f50',
    messagingSenderId: '827647189745',
    projectId: 'just-grab-8a0cd',
    storageBucket: 'just-grab-8a0cd.appspot.com',
    iosBundleId: 'com.example.justgrabDine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxnpHM5dx2wvydWSCGRWAJmrXkgSuXY-o',
    appId: '1:827647189745:web:fb3267b737841244717f50',
    messagingSenderId: '827647189745',
    projectId: 'just-grab-8a0cd',
    authDomain: 'just-grab-8a0cd.firebaseapp.com',
    storageBucket: 'just-grab-8a0cd.appspot.com',
    measurementId: 'G-XYSPMVR5ST',
  );
}
